### PR TITLE
Gui themes

### PR DESCRIPTION
**Pull request by SamuelBanya**
This is the draft so far, wanted to get your take to confirm this is good so far before adding the other sections. Just got around to working on this today.

Will work on adding the rest once you confirm this is correct, will probably have to figure out the logic behind the event handlers for the text fields too.

Changes proposed in this pull request:
- This will house the changes to include the GUI themes

@midwan

### CODE REVIEW

**Comment by midwan** [comment]
This fails to build :)

**Comment by SamuelBanya** [comment]
Good to know @midwan 

Is that going in the right direction before I proceed? Just wanted to touch base with you on that.

**Comment by midwan** [comment]
Get the latest from the `gui-themes` branch and take a look.
I've implemented most of the widgets there now, but it's not final yet.
There are some things that are still missing:
- Save functionality (the button is there, but doesn't do anything yet)
- Load functionality (same as above)
- Presets Dropdown

Also, the layout might change a bit, depends on how it looks best when the presets are added.

I think the idea is that we have a list of presets (maybe those that are found and parsed from a `themes` directory?), and when the user selects one, it gets loaded. So, the `Load` button might be obsolete in that case.

**Comment by SamuelBanya** [comment]
Hmm weird, I don't know why this closed my bad. All I did was basically take your branch, pull it to fast forward.

I then pushed it to the origin...

```
sam@Tinas-MacBook-Air ~/hub/amiberry (gui-themes) $ git pull upstream gui-themes --ff-only
From https://github.com/BlitterStudio/amiberry
 * branch              gui-themes -> FETCH_HEAD
fatal: Not possible to fast-forward, aborting.
sam@Tinas-MacBook-Air ~/hub/amiberry (gui-themes) $ git fetch upstream
From https://github.com/BlitterStudio/amiberry
   f8808b97..f252b4d0  master     -> upstream/master
   f7d83840..f252b4d0  preview    -> upstream/preview
sam@Tinas-MacBook-Air ~/hub/amiberry (gui-themes) $ git reset --hard upstream/gui-themes
HEAD is now at e41523de enhancement: added color box in PanelThemes
sam@Tinas-MacBook-Air ~/hub/amiberry (gui-themes) $ git push origin gui-themes --force
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:SamuelBanya/amiberry.git
 + 77acd116...e41523de gui-themes -> gui-themes (forced update)
```

Weird, I guess I'll open up another PR with that in mind, sorry about that.

**Comment by SamuelBanya** [comment]
Another question I have is, as I am doing changes, is there any way I can actively see it changing, or would I have to rebuild the entire project each time with the related cmake commands in the readme?

**Comment by SamuelBanya** [comment]
I did a little bit of progress here:
- https://github.com/SamuelBanya/amiberry/tree/gui-themes

Is what I have so far headed in the right direction? @midwan 

Asking on this closed PR since I'm not sure where else to ask unless you prefer the Pimiga discord channel instead. More so because I've only worked on work based BitBucket repos, and personal GitHub repos pushing to origin / main, or on branches, but haven't really dealt with upstream vs my branch in a while, so bear with me on that one.

**Comment by midwan** [comment]
It might be easier to take the details in either the Discussions page here, or on the Blitterstudio Discord server (link on the main Readme of this repo).

In short, you don't have to delete the object even. Rebuilding should automatically detect that the source file has changed there, and re-compile only that, then link it to the executable again. Since only one file was modified, the process should only take a few seconds. ;)

Bitbucket or Github repos don't matter, if the type of the repo is the same (Git), the process is also the same:
- Fork the original project (so then you have your own copy on your own repo)
- Clone the forked copy locally on your PC
- Work on it locally - create a new branch ideally, which will then be sent as a PR upstream (to the original repo you forked from)
- Test changes locally. They should build without problems, do what they are supposed to do, etc.
- When you are ready, open a PR against the upstream repo/branch you want to.
- If necessary, continue making changes to your fork/branch, they will be included in the PR. For example, some fixes might be required, or we may notice something you missed, etc.
- Any new PR will trigger an automated build on Github, to check that it works on all platforms. If those builds fail, that's something to fix/work on as well.
- If all goes well, the PR will eventually be approved/merged.

**Pull request closed without merging**
